'use strict';

/* 

79. Project 2: Modal Window:

Adding and removing classes is the main way in which we change styles on websites.
Select the elments that we need then store into a variable. Then we can use them over and over again.
HTML file: The hidden class is the main class that we will be working with.
Will NOT be creating the HTML for the modal window using JS. We only need to show it and to hide it, according to the clicks on the buttons.
The overlay is the darker part around the text box when the window is open.
We need to select the modal, the overlay, the close modal button and the show modal buttons. 

*/ 

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
// querySelectorAll: will give us a NodeList of all 3 of our buttons. A way of selecting multiple element within the the same class. Then do something for
// each of them, i.e. log their text content to the console.
const btnsOpenModal = document.querySelectorAll('.show-modal');
console.log(btnsOpenModal);

// a function expression.
const openModal = function() {
    // console.log('Button clicked');
    modal.classList.remove('hidden');
    overlay.classList.remove('hidden');
}

const closeModal = function() {
    modal.classList.add('hidden');
    overlay.classList.add('hidden');
};

// for-loop to Loop through the NodeList and do something to them. An array holding all the buttons.
// No need for braces to define the code body as only have one line of code to execute.
for (let i = 0; i < btnsOpenModal.length; i++)
// 3 of the text contents for 3 of the buttons.
// Attached an Event Handler function to each of the 3 buttons.
// Handler function: Instead of reading the text content property, We'll call the addEventListener method. Second argument is anonymous function which is also
// a function expression.
    // console.log(btnsOpenModal[i].textContent);
    btnsOpenModal[i].addEventListener('click', openModal);


// JavaScript will call this function
// Add the hidden class back-on which will hide the modal.
    btnCloseModal.addEventListener('click', closeModal);

    // Click outside of the modal, and the modal will close:
    overlay.addEventListener('click', closeModal);

/************************************************************************************************************************************************************** 

80. Working With Classes:

The code is above within 79. Modal window lecture.

************************************************************************************************************************************************************* */

/************************************************************************************************************************************************************** 

81. Handling an "Esc" Keypress Event:
Just an object generated by JS.
How to respond to keyboard events? Keypressdown event.
Event Object 'e':
This time we need to look at that event (not just listen and react to it) object in order to figure out which key was pressed. So we pass 'e' for event as an
argument. We don't call this but JS. 

************************************************************************************************************************************************************* */
 
// Keydown - define the function not call it here. This tell JS to cal this function when a keydown event happens and pass in the event object as an argument.
document.addEventListener('keydown', function (e) {
    // console.log('A key was pressed');
    // console.log(e.key); // what ever key we press on the UI we get the object info which tells us what key was pressed / about the event itself.
    // Read the property from the object 'e' the event object.
    console.log(e.key); // press the Enter key and that will show in the console.

    // If the pressed key (by the user) is Esc, and if the modal does not contain the hudden class, then execute this function to close the model.
    // Can nest 2 if-statements together, but best to write it all in one if statement.
    if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
            closeModal();
        }
});